profile=%4%fast

slang=%38%ind,id,eng,en,enUS,en-US,fi,fiFI,fi-FI
alang=ind,id,jpn,jp,ja,jap,eng,en,enUS,en-US,fi,fiFI,fi-FI
audio-pitch-correction=%3%yes
audio-file-auto=fuzzy												

demuxer-mkv-subtitle-preroll=%3%yes
embeddedfonts=%3%yes

gpu-context=%7%wayland
hwdec=%9%auto-safe
hwdec-codecs=%3%all
vo=%3%gpu
pulse-buffer=%2%50

osc=%2%no

save-position-on-quit=%3%yes
watch-later-options=start, sid									

sub-auto=fuzzy
sub-border-size=%3%3.2
sub-file-paths=%26%ass:srt:sub:subs:subtitles
sub-shadow-color=%9%#33000000
sub-shadow-offset=%1%1

ytdl-format=%57%bestvideo[height<=?1080][vcodec!~='av0?1']+bestaudio/best

msg-color=yes                           								
msg-module=yes                          								


